version: '3'
services:
  postgresql:
    image: 'postgres:latest'
  api:
    build:      
      context: .    
    #image: 'tszala/consumerhistory:latest'
    environment:      
      - PGUSER=postgres
      - PGHOST=postgresql
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    ports:
      - '8080:8080'
    depends_on:
      - postgresql